# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\fpd_explorer\res\inputBoxCenterOfMass.ui',
# licensing of '.\fpd_explorer\res\inputBoxCenterOfMass.ui' applies.
#
# Created: Fri Jan 24 21:15:23 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CenterofMass(object):
    def setupUi(self, CenterofMass):
        CenterofMass.setObjectName("CenterofMass")
        CenterofMass.resize(429, 116)
        self.verticalLayout = QtWidgets.QVBoxLayout(CenterofMass)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Ytext_2 = QtWidgets.QLineEdit(CenterofMass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Ytext_2.sizePolicy().hasHeightForWidth())
        self.Ytext_2.setSizePolicy(sizePolicy)
        self.Ytext_2.setCursor(QtCore.Qt.ArrowCursor)
        self.Ytext_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Ytext_2.setReadOnly(True)
        self.Ytext_2.setObjectName("Ytext_2")
        self.gridLayout.addWidget(self.Ytext_2, 1, 0, 1, 1)
        self.nc = QtWidgets.QSpinBox(CenterofMass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nc.sizePolicy().hasHeightForWidth())
        self.nc.setSizePolicy(sizePolicy)
        self.nc.setPrefix("")
        self.nc.setMinimum(0)
        self.nc.setMaximum(10000)
        self.nc.setSingleStep(1)
        self.nc.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.nc.setProperty("value", 16)
        self.nc.setObjectName("nc")
        self.gridLayout.addWidget(self.nc, 1, 1, 1, 1)
        self.nr = QtWidgets.QSpinBox(CenterofMass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nr.sizePolicy().hasHeightForWidth())
        self.nr.setSizePolicy(sizePolicy)
        self.nr.setPrefix("")
        self.nr.setMinimum(0)
        self.nr.setMaximum(10000)
        self.nr.setSingleStep(1)
        self.nr.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.nr.setProperty("value", 16)
        self.nr.setObjectName("nr")
        self.gridLayout.addWidget(self.nr, 0, 1, 1, 1)
        self.Ytext = QtWidgets.QLineEdit(CenterofMass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Ytext.sizePolicy().hasHeightForWidth())
        self.Ytext.setSizePolicy(sizePolicy)
        self.Ytext.setCursor(QtCore.Qt.ArrowCursor)
        self.Ytext.setFrame(True)
        self.Ytext.setAlignment(QtCore.Qt.AlignCenter)
        self.Ytext.setReadOnly(True)
        self.Ytext.setObjectName("Ytext")
        self.gridLayout.addWidget(self.Ytext, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(CenterofMass)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.restoreButton = QtWidgets.QPushButton(CenterofMass)
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout.addWidget(self.restoreButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CenterofMass)
        QtCore.QObject.connect(self.restoreButton, QtCore.SIGNAL("clicked()"), CenterofMass.restore_default)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CenterofMass.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CenterofMass.reject)
        QtCore.QMetaObject.connectSlotsByName(CenterofMass)

    def retranslateUi(self, CenterofMass):
        CenterofMass.setWindowTitle(QtWidgets.QApplication.translate("CenterofMass", "Center of Mass ", None, -1))
        self.Ytext_2.setText(QtWidgets.QApplication.translate("CenterofMass", "nc", None, -1))
        self.Ytext.setText(QtWidgets.QApplication.translate("CenterofMass", "nr", None, -1))
        self.restoreButton.setText(QtWidgets.QApplication.translate("CenterofMass", "Restore Default", None, -1))

