# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\fpd_explorer\res\inputBoxRemoveAperture.ui',
# licensing of '.\fpd_explorer\res\inputBoxRemoveAperture.ui' applies.
#
# Created: Fri Jan 24 21:15:24 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RemoveAperture(object):
    def setupUi(self, RemoveAperture):
        RemoveAperture.setObjectName("RemoveAperture")
        RemoveAperture.resize(429, 155)
        self.verticalLayout = QtWidgets.QVBoxLayout(RemoveAperture)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.add_radius = QtWidgets.QSpinBox(RemoveAperture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_radius.sizePolicy().hasHeightForWidth())
        self.add_radius.setSizePolicy(sizePolicy)
        self.add_radius.setPrefix("")
        self.add_radius.setMinimum(0)
        self.add_radius.setMaximum(10000)
        self.add_radius.setSingleStep(1)
        self.add_radius.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.add_radius.setProperty("value", 8)
        self.add_radius.setObjectName("add_radius")
        self.gridLayout.addWidget(self.add_radius, 1, 1, 1, 1)
        self.Ytext_2 = QtWidgets.QLineEdit(RemoveAperture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Ytext_2.sizePolicy().hasHeightForWidth())
        self.Ytext_2.setSizePolicy(sizePolicy)
        self.Ytext_2.setCursor(QtCore.Qt.ArrowCursor)
        self.Ytext_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Ytext_2.setReadOnly(True)
        self.Ytext_2.setObjectName("Ytext_2")
        self.gridLayout.addWidget(self.Ytext_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(RemoveAperture)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.aaf = QtWidgets.QSpinBox(RemoveAperture)
        self.aaf.setMaximum(1000)
        self.aaf.setProperty("value", 1)
        self.aaf.setObjectName("aaf")
        self.gridLayout.addWidget(self.aaf, 2, 1, 1, 1)
        self.Ytext = QtWidgets.QLineEdit(RemoveAperture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Ytext.sizePolicy().hasHeightForWidth())
        self.Ytext.setSizePolicy(sizePolicy)
        self.Ytext.setCursor(QtCore.Qt.ArrowCursor)
        self.Ytext.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Ytext.setReadOnly(True)
        self.Ytext.setObjectName("Ytext")
        self.gridLayout.addWidget(self.Ytext, 0, 0, 1, 1)
        self.sigma_val = QtWidgets.QSpinBox(RemoveAperture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sigma_val.sizePolicy().hasHeightForWidth())
        self.sigma_val.setSizePolicy(sizePolicy)
        self.sigma_val.setPrefix("")
        self.sigma_val.setMinimum(0)
        self.sigma_val.setMaximum(10000)
        self.sigma_val.setSingleStep(1)
        self.sigma_val.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.sigma_val.setProperty("value", 0)
        self.sigma_val.setObjectName("sigma_val")
        self.gridLayout.addWidget(self.sigma_val, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(RemoveAperture)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.restoreButton = QtWidgets.QPushButton(RemoveAperture)
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout.addWidget(self.restoreButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RemoveAperture)
        QtCore.QObject.connect(self.restoreButton, QtCore.SIGNAL("clicked()"), RemoveAperture.restore_default)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), RemoveAperture.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), RemoveAperture.reject)
        QtCore.QMetaObject.connectSlotsByName(RemoveAperture)

    def retranslateUi(self, RemoveAperture):
        RemoveAperture.setWindowTitle(QtWidgets.QApplication.translate("RemoveAperture", "Remove Aperture", None, -1))
        self.Ytext_2.setText(QtWidgets.QApplication.translate("RemoveAperture", "addition to radius ", None, -1))
        self.lineEdit.setText(QtWidgets.QApplication.translate("RemoveAperture", "aaf", None, -1))
        self.Ytext.setText(QtWidgets.QApplication.translate("RemoveAperture", "sigma value ", None, -1))
        self.restoreButton.setText(QtWidgets.QApplication.translate("RemoveAperture", "Restore Default", None, -1))

