# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

before_script:
  - sudo apt-get -qq update && sudo apt-get -qq install -y python
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y python python-virtualenv python-pip
  - sudo virtualenv venv
  - sudo venv/bin/activate

test:
  script:
    - pip install -r requirements.txt

run:
  script:
    - python compile_ui.py