# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homescreen.ui',
# licensing of 'homescreen.ui' applies.
#
# Created: Wed Nov 27 11:03:15 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1100, 800))
        self.tabWidget.setObjectName("tabWidget")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.home_tab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.resource_groupBox = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resource_groupBox.sizePolicy().hasHeightForWidth())
        self.resource_groupBox.setSizePolicy(sizePolicy)
        self.resource_groupBox.setMinimumSize(QtCore.QSize(500, 0))
        self.resource_groupBox.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.resource_groupBox.setFont(font)
        self.resource_groupBox.setObjectName("resource_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.resource_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hdf5_line_3 = QtWidgets.QLineEdit(self.resource_groupBox)
        self.hdf5_line_3.setAutoFillBackground(False)
        self.hdf5_line_3.setInputMask("")
        self.hdf5_line_3.setText("")
        self.hdf5_line_3.setReadOnly(True)
        self.hdf5_line_3.setClearButtonEnabled(True)
        self.hdf5_line_3.setObjectName("hdf5_line_3")
        self.gridLayout_4.addWidget(self.hdf5_line_3, 3, 1, 1, 4)
        self.pushButton_21 = QtWidgets.QPushButton(self.resource_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setCheckable(False)
        self.pushButton_21.setFlat(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_4.addWidget(self.pushButton_21, 4, 3, 1, 2)
        self.mib_line_3 = QtWidgets.QLineEdit(self.resource_groupBox)
        self.mib_line_3.setInputMask("")
        self.mib_line_3.setText("")
        self.mib_line_3.setReadOnly(True)
        self.mib_line_3.setClearButtonEnabled(True)
        self.mib_line_3.setObjectName("mib_line_3")
        self.gridLayout_4.addWidget(self.mib_line_3, 2, 1, 1, 4)
        self.pushButton_17 = QtWidgets.QPushButton(self.resource_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setCheckable(False)
        self.pushButton_17.setFlat(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_4.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.resource_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setCheckable(False)
        self.pushButton_16.setFlat(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_4.addWidget(self.pushButton_16, 2, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.resource_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setCheckable(False)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_4.addWidget(self.pushButton_18, 3, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.resource_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setCheckable(False)
        self.pushButton_19.setFlat(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_4.addWidget(self.pushButton_19, 4, 1, 1, 2)
        self.dm3_line_3 = QtWidgets.QLineEdit(self.resource_groupBox)
        self.dm3_line_3.setInputMask("")
        self.dm3_line_3.setText("")
        self.dm3_line_3.setReadOnly(True)
        self.dm3_line_3.setClearButtonEnabled(True)
        self.dm3_line_3.setObjectName("dm3_line_3")
        self.gridLayout_4.addWidget(self.dm3_line_3, 1, 1, 1, 4)
        self.gridLayout.addWidget(self.resource_groupBox, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 400))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 128, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(210, 80, 269, 39))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(170, 190, 295, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setCheckable(False)
        self.pushButton_20.setFlat(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_3.addWidget(self.pushButton_20)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setCheckable(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setCheckable(False)
        self.pushButton_14.setFlat(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.gridLayout.addWidget(self.groupBox_3, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.functions_groupBox = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functions_groupBox.sizePolicy().hasHeightForWidth())
        self.functions_groupBox.setSizePolicy(sizePolicy)
        self.functions_groupBox.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.functions_groupBox.setFont(font)
        self.functions_groupBox.setObjectName("functions_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.functions_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_43 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setCheckable(False)
        self.pushButton_43.setFlat(False)
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_3.addWidget(self.pushButton_43, 1, 1, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setCheckable(False)
        self.pushButton_39.setFlat(False)
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_3.addWidget(self.pushButton_39, 3, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setCheckable(False)
        self.pushButton_42.setFlat(False)
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_3.addWidget(self.pushButton_42, 2, 1, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setCheckable(False)
        self.pushButton_40.setFlat(False)
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_3.addWidget(self.pushButton_40, 0, 0, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setCheckable(False)
        self.pushButton_37.setFlat(False)
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_3.addWidget(self.pushButton_37, 2, 0, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setCheckable(False)
        self.pushButton_38.setFlat(False)
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_3.addWidget(self.pushButton_38, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.functions_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setCheckable(False)
        self.pushButton_41.setFlat(False)
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_3.addWidget(self.pushButton_41, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.functions_groupBox, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.file_groupBox = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_groupBox.sizePolicy().hasHeightForWidth())
        self.file_groupBox.setSizePolicy(sizePolicy)
        self.file_groupBox.setMinimumSize(QtCore.QSize(500, 0))
        self.file_groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.file_groupBox.setFont(font)
        self.file_groupBox.setObjectName("file_groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.file_groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mib_button = QtWidgets.QPushButton(self.file_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.mib_button.setFont(font)
        self.mib_button.setCheckable(False)
        self.mib_button.setFlat(False)
        self.mib_button.setObjectName("mib_button")
        self.horizontalLayout.addWidget(self.mib_button)
        self.dm3_button = QtWidgets.QPushButton(self.file_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.dm3_button.setFont(font)
        self.dm3_button.setCheckable(False)
        self.dm3_button.setFlat(False)
        self.dm3_button.setObjectName("dm3_button")
        self.horizontalLayout.addWidget(self.dm3_button)
        self.hdf5_button = QtWidgets.QPushButton(self.file_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.hdf5_button.setFont(font)
        self.hdf5_button.setCheckable(False)
        self.hdf5_button.setFlat(False)
        self.hdf5_button.setObjectName("hdf5_button")
        self.horizontalLayout.addWidget(self.hdf5_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mib_line = QtWidgets.QLineEdit(self.file_groupBox)
        self.mib_line.setInputMask("")
        self.mib_line.setText("")
        self.mib_line.setReadOnly(True)
        self.mib_line.setClearButtonEnabled(True)
        self.mib_line.setObjectName("mib_line")
        self.verticalLayout_3.addWidget(self.mib_line)
        self.dm3_line = QtWidgets.QLineEdit(self.file_groupBox)
        self.dm3_line.setInputMask("")
        self.dm3_line.setText("")
        self.dm3_line.setReadOnly(True)
        self.dm3_line.setClearButtonEnabled(True)
        self.dm3_line.setObjectName("dm3_line")
        self.verticalLayout_3.addWidget(self.dm3_line)
        self.hdf5_line = QtWidgets.QLineEdit(self.file_groupBox)
        self.hdf5_line.setAutoFillBackground(False)
        self.hdf5_line.setInputMask("")
        self.hdf5_line.setText("")
        self.hdf5_line.setReadOnly(True)
        self.hdf5_line.setClearButtonEnabled(True)
        self.hdf5_line.setObjectName("hdf5_line")
        self.verticalLayout_3.addWidget(self.hdf5_line)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_button = QtWidgets.QPushButton(self.file_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.load_button.setFont(font)
        self.load_button.setCheckable(False)
        self.load_button.setFlat(False)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_2.addWidget(self.load_button)
        self.clear_button = QtWidgets.QPushButton(self.file_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.clear_button.setFont(font)
        self.clear_button.setCheckable(False)
        self.clear_button.setFlat(False)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.file_groupBox, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        self.tabWidget.addTab(self.home_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_dm3 = QtWidgets.QAction(MainWindow)
        self.action_dm3.setObjectName("action_dm3")
        self.action_mib = QtWidgets.QAction(MainWindow)
        self.action_mib.setObjectName("action_mib")
        self.action_hdf5 = QtWidgets.QAction(MainWindow)
        self.action_hdf5.setObjectName("action_hdf5")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menuOpen.addAction(self.action_dm3)
        self.menuOpen.addAction(self.action_mib)
        self.menuOpen.addAction(self.action_hdf5)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuHelp.addAction(self.action_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.load_button, QtCore.SIGNAL("clicked()"), MainWindow.LoadFiles)
        QtCore.QObject.connect(self.mib_button, QtCore.SIGNAL("clicked()"), MainWindow.function_mib)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "fpd gui", None, -1))
        self.resource_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Resource monitor", None, -1))
        self.hdf5_line_3.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", ".hdf5 filename", None, -1))
        self.pushButton_21.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.mib_line_3.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", ".mib filename", None, -1))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("MainWindow", ".dm3", None, -1))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("MainWindow", ".mib", None, -1))
        self.pushButton_18.setText(QtWidgets.QApplication.translate("MainWindow", ".hdf5", None, -1))
        self.pushButton_19.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.dm3_line_3.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", ".dmr filename", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Workflow help", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "File opening", None, -1))
        self.pushButton_20.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.functions_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Functions", None, -1))
        self.pushButton_43.setText(QtWidgets.QApplication.translate("MainWindow", "Dummy", None, -1))
        self.pushButton_39.setText(QtWidgets.QApplication.translate("MainWindow", "center_of_mass", None, -1))
        self.pushButton_42.setText(QtWidgets.QApplication.translate("MainWindow", "Dummy", None, -1))
        self.pushButton_40.setText(QtWidgets.QApplication.translate("MainWindow", "DataBrowser", None, -1))
        self.pushButton_37.setText(QtWidgets.QApplication.translate("MainWindow", "synthetic_aperture", None, -1))
        self.pushButton_38.setText(QtWidgets.QApplication.translate("MainWindow", "find_circ_centre", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Dummy", None, -1))
        self.pushButton_41.setText(QtWidgets.QApplication.translate("MainWindow", "Dummy", None, -1))
        self.file_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "File opening", None, -1))
        self.mib_button.setText(QtWidgets.QApplication.translate("MainWindow", ".mib", None, -1))
        self.dm3_button.setText(QtWidgets.QApplication.translate("MainWindow", ".dm3", None, -1))
        self.hdf5_button.setText(QtWidgets.QApplication.translate("MainWindow", ".hdf5", None, -1))
        self.mib_line.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", ".mib filename", None, -1))
        self.dm3_line.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", ".dmr filename", None, -1))
        self.hdf5_line.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", ".hdf5 filename", None, -1))
        self.load_button.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.clear_button.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home_tab), QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Tab 2", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuOpen.setTitle(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.action_dm3.setText(QtWidgets.QApplication.translate("MainWindow", ".dm3", None, -1))
        self.action_mib.setText(QtWidgets.QApplication.translate("MainWindow", ".mib", None, -1))
        self.action_hdf5.setText(QtWidgets.QApplication.translate("MainWindow", ".hdf5", None, -1))
        self.action_about.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

