# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputbox.ui',
# licensing of 'inputbox.ui' applies.
#
# Created: Sun Nov 10 19:04:36 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_InputBox(object):
    def setupUi(self, InputBox):
        InputBox.setObjectName("InputBox")
        InputBox.resize(400, 112)
        InputBox.setMinimumSize(QtCore.QSize(400, 100))
        InputBox.setMaximumSize(QtCore.QSize(400, 112))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(InputBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Ysize = QtWidgets.QSpinBox(InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ysize.sizePolicy().hasHeightForWidth())
        self.Ysize.setSizePolicy(sizePolicy)
        self.Ysize.setMinimum(1)
        self.Ysize.setMaximum(13)
        self.Ysize.setSingleStep(1)
        self.Ysize.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.Ysize.setProperty("value", 8)
        self.Ysize.setObjectName("Ysize")
        self.gridLayout_6.addWidget(self.Ysize, 1, 1, 1, 1)
        self.Xsize = QtWidgets.QSpinBox(InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xsize.sizePolicy().hasHeightForWidth())
        self.Xsize.setSizePolicy(sizePolicy)
        self.Xsize.setWrapping(True)
        self.Xsize.setSuffix("")
        self.Xsize.setMinimum(1)
        self.Xsize.setMaximum(13)
        self.Xsize.setSingleStep(1)
        self.Xsize.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.Xsize.setProperty("value", 8)
        self.Xsize.setDisplayIntegerBase(10)
        self.Xsize.setObjectName("Xsize")
        self.gridLayout_6.addWidget(self.Xsize, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setCursor(QtCore.Qt.ArrowCursor)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setCursor(QtCore.Qt.ArrowCursor)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_6.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.yValue = QtWidgets.QLineEdit(InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yValue.sizePolicy().hasHeightForWidth())
        self.yValue.setSizePolicy(sizePolicy)
        self.yValue.setReadOnly(True)
        self.yValue.setObjectName("yValue")
        self.gridLayout_6.addWidget(self.yValue, 1, 2, 1, 1)
        self.xValue = QtWidgets.QLineEdit(InputBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xValue.sizePolicy().hasHeightForWidth())
        self.xValue.setSizePolicy(sizePolicy)
        self.xValue.setReadOnly(True)
        self.xValue.setObjectName("xValue")
        self.gridLayout_6.addWidget(self.xValue, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(InputBox)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(InputBox)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), InputBox.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), InputBox.reject)
        QtCore.QObject.connect(self.Xsize, QtCore.SIGNAL("valueChanged(int)"), InputBox.update_value)
        QtCore.QObject.connect(self.Ysize, QtCore.SIGNAL("valueChanged(int)"), InputBox.update_value)
        QtCore.QMetaObject.connectSlotsByName(InputBox)

    def retranslateUi(self, InputBox):
        InputBox.setWindowTitle(QtWidgets.QApplication.translate("InputBox", "Dialog", None, -1))
        self.Ysize.setPrefix(QtWidgets.QApplication.translate("InputBox", "2^", None, -1))
        self.Xsize.setPrefix(QtWidgets.QApplication.translate("InputBox", "2^", None, -1))
        self.lineEdit_4.setText(QtWidgets.QApplication.translate("InputBox", "X read size", None, -1))
        self.lineEdit_3.setText(QtWidgets.QApplication.translate("InputBox", "Y read size", None, -1))
        self.yValue.setText(QtWidgets.QApplication.translate("InputBox", "= 256", None, -1))
        self.xValue.setText(QtWidgets.QApplication.translate("InputBox", "= 256", None, -1))

